runtime: python27
threadsafe: yes
api_version: 1
service: dashboard

# Google App Engine's cache default expiration time is 10 minutes. It's suitable for most Production
# scenarios, but a shorter TTL may be desired for Development and QA, as it allows us to see a fresh
# code in action just a minute after the deployment.
default_expiration: 60s

handlers:
# Site root.
- url: /
  static_files: dist/vex/index.html
  upload: dist/vex/index.html
  secure: always

# catch-all rule
- url: /(.*\.(.+))$
  secure: always
  redirect_http_response_code: 301
  static_files: dist/vex/\1
  upload: dist/vex/(.*\.(.+))$

skip_files:
- ^(?!dist)
- node_modules/
- e2e/
